version: 2.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: boginw/markdown-pandoc:latest
    steps:
      - checkout
      - run:
          name: Compile Markdown
          command: ./scripts/build.sh
      - store_artifacts:
          path: ~/project/dist/output.pdf
          destination: output.pdf
  test:
    working_directory: ~/project/code
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout:
          path: ~/project
      - run: cp gradle.properties.default gradle.properties
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle :car:dependencies
      - run: gradle :ssr:dependencies
      - run: gradle :car:install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Run Gradle Tests
          command: gradle test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
